--require("tokyonight").setup({
--  style = "night",
--  transparent = true,
--  terminal_colors = true,
--  styles = {
--    comments = { italic = true },
--    keywords = { italic = true, bold = true },
--    functions = { bold = true },
--    variables = {},
--  }
--})
--
--vim.cmd[[colorscheme tokyonight]]
